name: Update

on:
  schedule:
    # every Saturday at 13:00 UTC
    - cron: "0 13 * * 6"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update dependencies
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
      - name: Update dependencies
        run: |-
          for repo in tree-sitter/tree-sitter tree-sitter/tree-sitter-c; do
            tag="$(gh release view -R "$repo" --json tagName -q .tagName)"
            zig fetch --save "https://github.com/$repo/archive/refs/tags/$tag.tar.gz"
          done
        env:
          GH_TOKEN: ${{github.token}}
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: build.zig.zon
          labels: dependencies
          commit-message: "build: update dependencies"
          title: "build: update dependencies"
          branch: update-zig-dependencies
          base: ${{github.head_ref}}
          token: ${{github.token}}
          delete-branch: true
          author: >-
            dependabot[bot]
            49699333+dependabot[bot]@users.noreply.github.com
